--- #YAML:1.0
name:               Math-NumberBase
version:            0.02
abstract:           Number converter from one base to another base
author:
    - Yehezkiel Syamsuhadi <yehezkielbs@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
build_requires:
    Test::NoWarnings: 0.084
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
